TRUNCATE TABLE ?:vendor_plans;

REPLACE INTO ?:vendor_plans (`plan_id`, `status`, `position`, `is_default`, `price`, `periodicity`, `commission`, `products_limit`, `revenue_limit`, `vendor_store`, `categories`) VALUES (1,'A',20,0,100.00,'month',10.00,1000,1000.00,1,'');
REPLACE INTO ?:vendor_plans (`plan_id`, `status`, `position`, `is_default`, `price`, `periodicity`, `commission`, `products_limit`, `revenue_limit`, `vendor_store`, `categories`) VALUES (2,'A',10,0,0.00,'month',20.00,25,500.00,0,'');
REPLACE INTO ?:vendor_plans (`plan_id`, `status`, `position`, `is_default`, `price`, `periodicity`, `commission`, `products_limit`, `revenue_limit`, `vendor_store`, `categories`) VALUES (3,'A',30,1,250.00,'month',5.00,10000,10000.00,1,'');
REPLACE INTO ?:vendor_plans (`plan_id`, `status`, `position`, `is_default`, `price`, `periodicity`, `commission`, `products_limit`, `revenue_limit`, `vendor_store`, `categories`) VALUES (4,'A',40,0,1000.00,'month',1.00,100000,0.00,1,'');
REPLACE INTO ?:vendor_plans (`plan_id`, `status`, `position`, `is_default`, `price`, `periodicity`, `commission`, `products_limit`, `revenue_limit`, `vendor_store`, `categories`) VALUES (5,'H',0,0,200.00,'month',4.50,12500,15000.00,1,'');

UPDATE ?:companies SET plan_id = 4 WHERE company_id = 1;
UPDATE ?:companies SET plan_id = 5 WHERE company_id = 2;
UPDATE ?:companies SET plan_id = 3 WHERE company_id = 3;
UPDATE ?:companies SET plan_id = 1 WHERE company_id = 4;
UPDATE ?:companies SET plan_id = 1 WHERE company_id = 5;
UPDATE ?:companies SET plan_id = 1 WHERE company_id = 6;
UPDATE ?:companies SET plan_id = 1 WHERE company_id = 7;
UPDATE ?:companies SET plan_id = 1 WHERE company_id = 8;
UPDATE ?:companies SET plan_id = 3 WHERE company_id = 9;
UPDATE ?:companies SET plan_id = 3 WHERE company_id = 10;
UPDATE ?:companies SET plan_id = 3 WHERE company_id = 11;
UPDATE ?:companies SET plan_id = 3 WHERE company_id = 12;

REPLACE INTO ?:vendor_payouts (`payout_id`, `company_id`, `order_id`, `payout_date`, `start_date`, `end_date`, `payout_amount`, `order_amount`, `payment_method`, `comments`, `plan_id`, `commission_amount`, `commission`, `commission_type`, `payout_type`, `approval_status`) VALUES (1,1,0,1482394748,1482394748,1482394748,100.00,0.00,'Plan: Silver',NULL,1,0.00,0.00,'A','payout','C');
REPLACE INTO ?:vendor_payouts (`payout_id`, `company_id`, `order_id`, `payout_date`, `start_date`, `end_date`, `payout_amount`, `order_amount`, `payment_method`, `comments`, `plan_id`, `commission_amount`, `commission`, `commission_type`, `payout_type`, `approval_status`) VALUES (2,2,0,1482394748,1482394748,1482394748,100.00,0.00,'Plan: Silver',NULL,1,0.00,0.00,'A','payout','C');
REPLACE INTO ?:vendor_payouts (`payout_id`, `company_id`, `order_id`, `payout_date`, `start_date`, `end_date`, `payout_amount`, `order_amount`, `payment_method`, `comments`, `plan_id`, `commission_amount`, `commission`, `commission_type`, `payout_type`, `approval_status`) VALUES (3,1,0,1482394794,1482394794,1482394794,1000.00,0.00,'Plan: Platinum',NULL,4,0.00,0.00,'A','payout','C');
REPLACE INTO ?:vendor_payouts (`payout_id`, `company_id`, `order_id`, `payout_date`, `start_date`, `end_date`, `payout_amount`, `order_amount`, `payment_method`, `comments`, `plan_id`, `commission_amount`, `commission`, `commission_type`, `payout_type`, `approval_status`) VALUES (4,3,0,1482394803,1482394803,1482394803,250.00,0.00,'Plan: Gold',NULL,3,0.00,0.00,'A','payout','C');
REPLACE INTO ?:vendor_payouts (`payout_id`, `company_id`, `order_id`, `payout_date`, `start_date`, `end_date`, `payout_amount`, `order_amount`, `payment_method`, `comments`, `plan_id`, `commission_amount`, `commission`, `commission_type`, `payout_type`, `approval_status`) VALUES (5,2,0,1482394810,1482394810,1482394810,250.00,0.00,'Plan: Gold',NULL,3,0.00,0.00,'A','payout','C');
REPLACE INTO ?:vendor_payouts (`payout_id`, `company_id`, `order_id`, `payout_date`, `start_date`, `end_date`, `payout_amount`, `order_amount`, `payment_method`, `comments`, `plan_id`, `commission_amount`, `commission`, `commission_type`, `payout_type`, `approval_status`) VALUES (6,3,0,1482394748,1482394748,1482394748,100.00,0.00,'Plan: Silver',NULL,1,0.00,0.00,'A','payout','C');
REPLACE INTO ?:vendor_payouts (`payout_id`, `company_id`, `order_id`, `payout_date`, `start_date`, `end_date`, `payout_amount`, `order_amount`, `payment_method`, `comments`, `plan_id`, `commission_amount`, `commission`, `commission_type`, `payout_type`, `approval_status`) VALUES (7,4,0,1482394748,1482394748,1482394748,100.00,0.00,'Plan: Silver',NULL,1,0.00,0.00,'A','payout','C');
REPLACE INTO ?:vendor_payouts (`payout_id`, `company_id`, `order_id`, `payout_date`, `start_date`, `end_date`, `payout_amount`, `order_amount`, `payment_method`, `comments`, `plan_id`, `commission_amount`, `commission`, `commission_type`, `payout_type`, `approval_status`) VALUES (8,5,0,1482394748,1482394748,1482394748,100.00,0.00,'Plan: Silver',NULL,1,0.00,0.00,'A','payout','C');
REPLACE INTO ?:vendor_payouts (`payout_id`, `company_id`, `order_id`, `payout_date`, `start_date`, `end_date`, `payout_amount`, `order_amount`, `payment_method`, `comments`, `plan_id`, `commission_amount`, `commission`, `commission_type`, `payout_type`, `approval_status`) VALUES (9,6,0,1482394748,1482394748,1482394748,100.00,0.00,'Plan: Silver',NULL,1,0.00,0.00,'A','payout','C');
REPLACE INTO ?:vendor_payouts (`payout_id`, `company_id`, `order_id`, `payout_date`, `start_date`, `end_date`, `payout_amount`, `order_amount`, `payment_method`, `comments`, `plan_id`, `commission_amount`, `commission`, `commission_type`, `payout_type`, `approval_status`) VALUES (10,7,0,1482394748,1482394748,1482394748,100.00,0.00,'Plan: Silver',NULL,1,0.00,0.00,'A','payout','C');
REPLACE INTO ?:vendor_payouts (`payout_id`, `company_id`, `order_id`, `payout_date`, `start_date`, `end_date`, `payout_amount`, `order_amount`, `payment_method`, `comments`, `plan_id`, `commission_amount`, `commission`, `commission_type`, `payout_type`, `approval_status`) VALUES (11,8,0,1482394748,1482394748,1482394748,100.00,0.00,'Plan: Silver',NULL,1,0.00,0.00,'A','payout','C');
REPLACE INTO ?:vendor_payouts (`payout_id`, `company_id`, `order_id`, `payout_date`, `start_date`, `end_date`, `payout_amount`, `order_amount`, `payment_method`, `comments`, `plan_id`, `commission_amount`, `commission`, `commission_type`, `payout_type`, `approval_status`) VALUES (12,9,0,1482395741,1482395741,1482395741,250.00,0.00,'Plan: Gold',NULL,3,0.00,0.00,'A','payout','C');
REPLACE INTO ?:vendor_payouts (`payout_id`, `company_id`, `order_id`, `payout_date`, `start_date`, `end_date`, `payout_amount`, `order_amount`, `payment_method`, `comments`, `plan_id`, `commission_amount`, `commission`, `commission_type`, `payout_type`, `approval_status`) VALUES (13,10,0,1482396924,1482396924,1482396924,250.00,0.00,'Plan: Gold',NULL,3,0.00,0.00,'A','payout','C');
REPLACE INTO ?:vendor_payouts (`payout_id`, `company_id`, `order_id`, `payout_date`, `start_date`, `end_date`, `payout_amount`, `order_amount`, `payment_method`, `comments`, `plan_id`, `commission_amount`, `commission`, `commission_type`, `payout_type`, `approval_status`) VALUES (14,11,0,1482397344,1482397344,1482397344,250.00,0.00,'Plan: Gold',NULL,3,0.00,0.00,'A','payout','C');
REPLACE INTO ?:vendor_payouts (`payout_id`, `company_id`, `order_id`, `payout_date`, `start_date`, `end_date`, `payout_amount`, `order_amount`, `payment_method`, `comments`, `plan_id`, `commission_amount`, `commission`, `commission_type`, `payout_type`, `approval_status`) VALUES (15,12,0,1482397928,1482397928,1482397928,250.00,0.00,'Plan: Gold',NULL,3,0.00,0.00,'A','payout','C');
REPLACE INTO ?:vendor_payouts (`payout_id`, `company_id`, `order_id`, `payout_date`, `start_date`, `end_date`, `payout_amount`, `order_amount`, `payment_method`, `comments`, `plan_id`, `commission_amount`, `commission`, `commission_type`, `payout_type`, `approval_status`) VALUES (21,8,0,1483009004,1483009004,1483009004,100.00,0.00,'Plan: Silver',NULL,1,0.00,0.00,'A','payout','C');
REPLACE INTO ?:vendor_payouts (`payout_id`, `company_id`, `order_id`, `payout_date`, `start_date`, `end_date`, `payout_amount`, `order_amount`, `payment_method`, `comments`, `plan_id`, `commission_amount`, `commission`, `commission_type`, `payout_type`, `approval_status`) VALUES (174,1,0,1485073194,1485073194,1485073194,1000.00,0.00,'Plan: Platinum',NULL,4,0.00,0.00,'A','payout','C');
REPLACE INTO ?:vendor_payouts (`payout_id`, `company_id`, `order_id`, `payout_date`, `start_date`, `end_date`, `payout_amount`, `order_amount`, `payment_method`, `comments`, `plan_id`, `commission_amount`, `commission`, `commission_type`, `payout_type`, `approval_status`) VALUES (175,2,0,1485073210,1485073210,1485073210,250.00,0.00,'Plan: Gold',NULL,3,0.00,0.00,'A','payout','C');
REPLACE INTO ?:vendor_payouts (`payout_id`, `company_id`, `order_id`, `payout_date`, `start_date`, `end_date`, `payout_amount`, `order_amount`, `payment_method`, `comments`, `plan_id`, `commission_amount`, `commission`, `commission_type`, `payout_type`, `approval_status`) VALUES (176,3,0,1485073203,1485073203,1485073203,250.00,0.00,'Plan: Gold',NULL,3,0.00,0.00,'A','payout','C');
REPLACE INTO ?:vendor_payouts (`payout_id`, `company_id`, `order_id`, `payout_date`, `start_date`, `end_date`, `payout_amount`, `order_amount`, `payment_method`, `comments`, `plan_id`, `commission_amount`, `commission`, `commission_type`, `payout_type`, `approval_status`) VALUES (177,4,0,1485073148,1485073148,1485073148,100.00,0.00,'Plan: Silver',NULL,1,0.00,0.00,'A','payout','C');
REPLACE INTO ?:vendor_payouts (`payout_id`, `company_id`, `order_id`, `payout_date`, `start_date`, `end_date`, `payout_amount`, `order_amount`, `payment_method`, `comments`, `plan_id`, `commission_amount`, `commission`, `commission_type`, `payout_type`, `approval_status`) VALUES (178,5,0,1485073148,1485073148,1485073148,100.00,0.00,'Plan: Silver',NULL,1,0.00,0.00,'A','payout','C');
REPLACE INTO ?:vendor_payouts (`payout_id`, `company_id`, `order_id`, `payout_date`, `start_date`, `end_date`, `payout_amount`, `order_amount`, `payment_method`, `comments`, `plan_id`, `commission_amount`, `commission`, `commission_type`, `payout_type`, `approval_status`) VALUES (179,6,0,1485073148,1485073148,1485073148,100.00,0.00,'Plan: Silver',NULL,1,0.00,0.00,'A','payout','C');
REPLACE INTO ?:vendor_payouts (`payout_id`, `company_id`, `order_id`, `payout_date`, `start_date`, `end_date`, `payout_amount`, `order_amount`, `payment_method`, `comments`, `plan_id`, `commission_amount`, `commission`, `commission_type`, `payout_type`, `approval_status`) VALUES (180,7,0,1485073148,1485073148,1485073148,100.00,0.00,'Plan: Silver',NULL,1,0.00,0.00,'A','payout','C');
REPLACE INTO ?:vendor_payouts (`payout_id`, `company_id`, `order_id`, `payout_date`, `start_date`, `end_date`, `payout_amount`, `order_amount`, `payment_method`, `comments`, `plan_id`, `commission_amount`, `commission`, `commission_type`, `payout_type`, `approval_status`) VALUES (181,9,0,1485074141,1485074141,1485074141,250.00,0.00,'Plan: Gold',NULL,3,0.00,0.00,'A','payout','C');
REPLACE INTO ?:vendor_payouts (`payout_id`, `company_id`, `order_id`, `payout_date`, `start_date`, `end_date`, `payout_amount`, `order_amount`, `payment_method`, `comments`, `plan_id`, `commission_amount`, `commission`, `commission_type`, `payout_type`, `approval_status`) VALUES (182,10,0,1485075324,1485075324,1485075324,250.00,0.00,'Plan: Gold',NULL,3,0.00,0.00,'A','payout','C');
REPLACE INTO ?:vendor_payouts (`payout_id`, `company_id`, `order_id`, `payout_date`, `start_date`, `end_date`, `payout_amount`, `order_amount`, `payment_method`, `comments`, `plan_id`, `commission_amount`, `commission`, `commission_type`, `payout_type`, `approval_status`) VALUES (183,11,0,1485075744,1485075744,1485075744,250.00,0.00,'Plan: Gold',NULL,3,0.00,0.00,'A','payout','C');
REPLACE INTO ?:vendor_payouts (`payout_id`, `company_id`, `order_id`, `payout_date`, `start_date`, `end_date`, `payout_amount`, `order_amount`, `payment_method`, `comments`, `plan_id`, `commission_amount`, `commission`, `commission_type`, `payout_type`, `approval_status`) VALUES (184,12,0,1485076328,1485076328,1485076328,250.00,0.00,'Plan: Gold',NULL,3,0.00,0.00,'A','payout','C');
REPLACE INTO ?:vendor_payouts (`payout_id`, `company_id`, `order_id`, `payout_date`, `start_date`, `end_date`, `payout_amount`, `order_amount`, `payment_method`, `comments`, `plan_id`, `commission_amount`, `commission`, `commission_type`, `payout_type`, `approval_status`) VALUES (209,8,0,1485687404,1485687404,1485687404,100.00,0.00,'Plan: Silver',NULL,1,0.00,0.00,'A','payout','C');
REPLACE INTO ?:vendor_payouts (`payout_id`, `company_id`, `order_id`, `payout_date`, `start_date`, `end_date`, `payout_amount`, `order_amount`, `payment_method`, `comments`, `plan_id`, `commission_amount`, `commission`, `commission_type`, `payout_type`, `approval_status`) VALUES (256,2,0,1486730586,1486730586,1486730586,200.00,0.00,'','Payout for the vendor plan: Exclusive',5,0.00,0.00,'A','payout','P');

UPDATE ?:vendor_payouts SET commission_amount = 6.65, commission = 5.00, commission_type = 'P' WHERE payout_id = 16;
UPDATE ?:vendor_payouts SET commission_amount = 4.44, commission = 1.00, commission_type = 'P' WHERE payout_id = 17;
UPDATE ?:vendor_payouts SET commission_amount = 22.85, commission = 5.00, commission_type = 'P' WHERE payout_id = 18;
UPDATE ?:vendor_payouts SET commission_amount = 24.00, commission = 5.00, commission_type = 'P' WHERE payout_id = 19;
UPDATE ?:vendor_payouts SET commission_amount = 47.20, commission = 5.00, commission_type = 'P' WHERE payout_id = 20;
UPDATE ?:vendor_payouts SET commission_amount = 4.54, commission = 1.00, commission_type = 'P' WHERE payout_id = 22;
UPDATE ?:vendor_payouts SET commission_amount = 3.47, commission = 1.00, commission_type = 'P' WHERE payout_id = 23;
UPDATE ?:vendor_payouts SET commission_amount = 4.41, commission = 1.00, commission_type = 'P' WHERE payout_id = 24;
UPDATE ?:vendor_payouts SET commission_amount = 2.60, commission = 1.00, commission_type = 'P' WHERE payout_id = 25;
UPDATE ?:vendor_payouts SET commission_amount = 2.38, commission = 1.00, commission_type = 'P' WHERE payout_id = 26;
UPDATE ?:vendor_payouts SET commission_amount = 2.82, commission = 1.00, commission_type = 'P' WHERE payout_id = 27;
UPDATE ?:vendor_payouts SET commission_amount = 8.28, commission = 1.00, commission_type = 'P' WHERE payout_id = 28;
UPDATE ?:vendor_payouts SET commission_amount = 4.35, commission = 1.00, commission_type = 'P' WHERE payout_id = 29;
UPDATE ?:vendor_payouts SET commission_amount = 3.34, commission = 1.00, commission_type = 'P' WHERE payout_id = 30;
UPDATE ?:vendor_payouts SET commission_amount = 60.70, commission = 10.00, commission_type = 'P' WHERE payout_id = 31;
UPDATE ?:vendor_payouts SET commission_amount = 5.16, commission = 1.00, commission_type = 'P' WHERE payout_id = 32;
UPDATE ?:vendor_payouts SET commission_amount = 22.00, commission = 10.00, commission_type = 'P' WHERE payout_id = 33;
UPDATE ?:vendor_payouts SET commission_amount = 44.80, commission = 10.00, commission_type = 'P' WHERE payout_id = 34;
UPDATE ?:vendor_payouts SET commission_amount = 3.77, commission = 1.00, commission_type = 'P' WHERE payout_id = 35;
UPDATE ?:vendor_payouts SET commission_amount = 34.70, commission = 10.00, commission_type = 'P' WHERE payout_id = 36;
UPDATE ?:vendor_payouts SET commission_amount = 20.50, commission = 5.00, commission_type = 'P' WHERE payout_id = 37;
UPDATE ?:vendor_payouts SET commission_amount = 8.55, commission = 5.00, commission_type = 'P' WHERE payout_id = 38;
UPDATE ?:vendor_payouts SET commission_amount = 41.60, commission = 10.00, commission_type = 'P' WHERE payout_id = 39;
UPDATE ?:vendor_payouts SET commission_amount = 24.20, commission = 10.00, commission_type = 'P' WHERE payout_id = 40;
UPDATE ?:vendor_payouts SET commission_amount = 6.70, commission = 5.00, commission_type = 'P' WHERE payout_id = 41;
UPDATE ?:vendor_payouts SET commission_amount = 41.60, commission = 10.00, commission_type = 'P' WHERE payout_id = 42;
UPDATE ?:vendor_payouts SET commission_amount = 6.50, commission = 5.00, commission_type = 'P' WHERE payout_id = 43;
UPDATE ?:vendor_payouts SET commission_amount = 15.85, commission = 5.00, commission_type = 'P' WHERE payout_id = 44;
UPDATE ?:vendor_payouts SET commission_amount = 36.10, commission = 10.00, commission_type = 'P' WHERE payout_id = 45;
UPDATE ?:vendor_payouts SET commission_amount = 38.60, commission = 10.00, commission_type = 'P' WHERE payout_id = 46;
UPDATE ?:vendor_payouts SET commission_amount = 15.45, commission = 5.00, commission_type = 'P' WHERE payout_id = 47;
UPDATE ?:vendor_payouts SET commission_amount = 8.40, commission = 5.00, commission_type = 'P' WHERE payout_id = 48;
UPDATE ?:vendor_payouts SET commission_amount = 25.75, commission = 5.00, commission_type = 'P' WHERE payout_id = 49;
UPDATE ?:vendor_payouts SET commission_amount = 12.75, commission = 5.00, commission_type = 'P' WHERE payout_id = 50;
UPDATE ?:vendor_payouts SET commission_amount = 25.75, commission = 5.00, commission_type = 'P' WHERE payout_id = 51;
UPDATE ?:vendor_payouts SET commission_amount = 33.70, commission = 10.00, commission_type = 'P' WHERE payout_id = 52;
UPDATE ?:vendor_payouts SET commission_amount = 8.35, commission = 5.00, commission_type = 'P' WHERE payout_id = 53;
UPDATE ?:vendor_payouts SET commission_amount = 12.90, commission = 5.00, commission_type = 'P' WHERE payout_id = 54;
UPDATE ?:vendor_payouts SET commission_amount = 20.20, commission = 10.00, commission_type = 'P' WHERE payout_id = 55;
UPDATE ?:vendor_payouts SET commission_amount = 45.20, commission = 10.00, commission_type = 'P' WHERE payout_id = 56;
UPDATE ?:vendor_payouts SET commission_amount = 7.20, commission = 5.00, commission_type = 'P' WHERE payout_id = 57;
UPDATE ?:vendor_payouts SET commission_amount = 17.00, commission = 5.00, commission_type = 'P' WHERE payout_id = 58;
UPDATE ?:vendor_payouts SET commission_amount = 46.50, commission = 10.00, commission_type = 'P' WHERE payout_id = 59;
UPDATE ?:vendor_payouts SET commission_amount = 16.15, commission = 5.00, commission_type = 'P' WHERE payout_id = 60;
UPDATE ?:vendor_payouts SET commission_amount = 7.20, commission = 5.00, commission_type = 'P' WHERE payout_id = 61;
UPDATE ?:vendor_payouts SET commission_amount = 17.25, commission = 5.00, commission_type = 'P' WHERE payout_id = 62;
UPDATE ?:vendor_payouts SET commission_amount = 22.90, commission = 5.00, commission_type = 'P' WHERE payout_id = 63;
UPDATE ?:vendor_payouts SET commission_amount = 15.50, commission = 5.00, commission_type = 'P' WHERE payout_id = 64;
UPDATE ?:vendor_payouts SET commission_amount = 47.80, commission = 10.00, commission_type = 'P' WHERE payout_id = 65;
UPDATE ?:vendor_payouts SET commission_amount = 9.05, commission = 5.00, commission_type = 'P' WHERE payout_id = 66;
UPDATE ?:vendor_payouts SET commission_amount = 44.80, commission = 10.00, commission_type = 'P' WHERE payout_id = 67;
UPDATE ?:vendor_payouts SET commission_amount = 20.95, commission = 5.00, commission_type = 'P' WHERE payout_id = 68;
UPDATE ?:vendor_payouts SET commission_amount = 15.85, commission = 5.00, commission_type = 'P' WHERE payout_id = 69;
UPDATE ?:vendor_payouts SET commission_amount = 12.40, commission = 5.00, commission_type = 'P' WHERE payout_id = 70;
UPDATE ?:vendor_payouts SET commission_amount = 17.45, commission = 5.00, commission_type = 'P' WHERE payout_id = 71;
UPDATE ?:vendor_payouts SET commission_amount = 46.50, commission = 10.00, commission_type = 'P' WHERE payout_id = 72;
UPDATE ?:vendor_payouts SET commission_amount = 21.20, commission = 10.00, commission_type = 'P' WHERE payout_id = 73;
UPDATE ?:vendor_payouts SET commission_amount = 10.65, commission = 5.00, commission_type = 'P' WHERE payout_id = 74;
UPDATE ?:vendor_payouts SET commission_amount = 18.05, commission = 5.00, commission_type = 'P' WHERE payout_id = 75;
UPDATE ?:vendor_payouts SET commission_amount = 31.80, commission = 10.00, commission_type = 'P' WHERE payout_id = 76;
UPDATE ?:vendor_payouts SET commission_amount = 18.15, commission = 5.00, commission_type = 'P' WHERE payout_id = 77;
UPDATE ?:vendor_payouts SET commission_amount = 23.65, commission = 5.00, commission_type = 'P' WHERE payout_id = 78;
UPDATE ?:vendor_payouts SET commission_amount = 45.40, commission = 10.00, commission_type = 'P' WHERE payout_id = 79;
UPDATE ?:vendor_payouts SET commission_amount = 19.60, commission = 10.00, commission_type = 'P' WHERE payout_id = 80;
UPDATE ?:vendor_payouts SET commission_amount = 23.30, commission = 5.00, commission_type = 'P' WHERE payout_id = 81;
UPDATE ?:vendor_payouts SET commission_amount = 24.25, commission = 5.00, commission_type = 'P' WHERE payout_id = 82;
UPDATE ?:vendor_payouts SET commission_amount = 12.90, commission = 5.00, commission_type = 'P' WHERE payout_id = 83;
UPDATE ?:vendor_payouts SET commission_amount = 46.70, commission = 10.00, commission_type = 'P' WHERE payout_id = 84;
UPDATE ?:vendor_payouts SET commission_amount = 6.60, commission = 5.00, commission_type = 'P' WHERE payout_id = 85;
UPDATE ?:vendor_payouts SET commission_amount = 9.30, commission = 5.00, commission_type = 'P' WHERE payout_id = 86;
UPDATE ?:vendor_payouts SET commission_amount = 31.15, commission = 5.00, commission_type = 'P' WHERE payout_id = 87;
UPDATE ?:vendor_payouts SET commission_amount = 24.80, commission = 10.00, commission_type = 'P' WHERE payout_id = 88;
UPDATE ?:vendor_payouts SET commission_amount = 7.40, commission = 5.00, commission_type = 'P' WHERE payout_id = 89;
UPDATE ?:vendor_payouts SET commission_amount = 30.35, commission = 5.00, commission_type = 'P' WHERE payout_id = 90;
UPDATE ?:vendor_payouts SET commission_amount = 9.05, commission = 5.00, commission_type = 'P' WHERE payout_id = 91;
UPDATE ?:vendor_payouts SET commission_amount = 38.60, commission = 10.00, commission_type = 'P' WHERE payout_id = 92;
UPDATE ?:vendor_payouts SET commission_amount = 31.20, commission = 5.00, commission_type = 'P' WHERE payout_id = 93;
UPDATE ?:vendor_payouts SET commission_amount = 56.20, commission = 10.00, commission_type = 'P' WHERE payout_id = 94;
UPDATE ?:vendor_payouts SET commission_amount = 20.25, commission = 5.00, commission_type = 'P' WHERE payout_id = 95;
UPDATE ?:vendor_payouts SET commission_amount = 41.80, commission = 5.00, commission_type = 'P' WHERE payout_id = 96;
UPDATE ?:vendor_payouts SET commission_amount = 20.60, commission = 10.00, commission_type = 'P' WHERE payout_id = 97;
UPDATE ?:vendor_payouts SET commission_amount = 39.50, commission = 10.00, commission_type = 'P' WHERE payout_id = 98;
UPDATE ?:vendor_payouts SET commission_amount = 22.30, commission = 5.00, commission_type = 'P' WHERE payout_id = 99;
UPDATE ?:vendor_payouts SET commission_amount = 24.45, commission = 5.00, commission_type = 'P' WHERE payout_id = 100;
UPDATE ?:vendor_payouts SET commission_amount = 32.10, commission = 5.00, commission_type = 'P' WHERE payout_id = 101;
UPDATE ?:vendor_payouts SET commission_amount = 15.85, commission = 5.00, commission_type = 'P' WHERE payout_id = 102;
UPDATE ?:vendor_payouts SET commission_amount = 23.80, commission = 10.00, commission_type = 'P' WHERE payout_id = 103;
UPDATE ?:vendor_payouts SET commission_amount = 45.80, commission = 5.00, commission_type = 'P' WHERE payout_id = 104;
UPDATE ?:vendor_payouts SET commission_amount = 6.70, commission = 5.00, commission_type = 'P' WHERE payout_id = 105;
UPDATE ?:vendor_payouts SET commission_amount = 6.65, commission = 5.00, commission_type = 'P' WHERE payout_id = 106;
UPDATE ?:vendor_payouts SET commission_amount = 54.70, commission = 10.00, commission_type = 'P' WHERE payout_id = 107;
UPDATE ?:vendor_payouts SET commission_amount = 18.90, commission = 5.00, commission_type = 'P' WHERE payout_id = 108;
UPDATE ?:vendor_payouts SET commission_amount = 9.65, commission = 5.00, commission_type = 'P' WHERE payout_id = 109;
UPDATE ?:vendor_payouts SET commission_amount = 6.95, commission = 5.00, commission_type = 'P' WHERE payout_id = 110;
UPDATE ?:vendor_payouts SET commission_amount = 31.80, commission = 10.00, commission_type = 'P' WHERE payout_id = 111;
UPDATE ?:vendor_payouts SET commission_amount = 49.70, commission = 10.00, commission_type = 'P' WHERE payout_id = 112;
UPDATE ?:vendor_payouts SET commission_amount = 42.80, commission = 10.00, commission_type = 'P' WHERE payout_id = 113;
UPDATE ?:vendor_payouts SET commission_amount = 16.75, commission = 5.00, commission_type = 'P' WHERE payout_id = 114;
UPDATE ?:vendor_payouts SET commission_amount = 22.70, commission = 5.00, commission_type = 'P' WHERE payout_id = 115;
UPDATE ?:vendor_payouts SET commission_amount = 7.20, commission = 5.00, commission_type = 'P' WHERE payout_id = 116;
UPDATE ?:vendor_payouts SET commission_amount = 37.30, commission = 10.00, commission_type = 'P' WHERE payout_id = 117;
UPDATE ?:vendor_payouts SET commission_amount = 92.80, commission = 10.00, commission_type = 'P' WHERE payout_id = 118;
UPDATE ?:vendor_payouts SET commission_amount = 30.70, commission = 10.00, commission_type = 'P' WHERE payout_id = 119;
UPDATE ?:vendor_payouts SET commission_amount = 45.20, commission = 10.00, commission_type = 'P' WHERE payout_id = 120;
UPDATE ?:vendor_payouts SET commission_amount = 23.60, commission = 10.00, commission_type = 'P' WHERE payout_id = 121;
UPDATE ?:vendor_payouts SET commission_amount = 7.55, commission = 5.00, commission_type = 'P' WHERE payout_id = 122;
UPDATE ?:vendor_payouts SET commission_amount = 16.15, commission = 5.00, commission_type = 'P' WHERE payout_id = 123;
UPDATE ?:vendor_payouts SET commission_amount = 22.30, commission = 5.00, commission_type = 'P' WHERE payout_id = 124;
UPDATE ?:vendor_payouts SET commission_amount = 12.75, commission = 5.00, commission_type = 'P' WHERE payout_id = 125;
UPDATE ?:vendor_payouts SET commission_amount = 14.50, commission = 5.00, commission_type = 'P' WHERE payout_id = 126;
UPDATE ?:vendor_payouts SET commission_amount = 42.40, commission = 10.00, commission_type = 'P' WHERE payout_id = 127;
UPDATE ?:vendor_payouts SET commission_amount = 13.75, commission = 5.00, commission_type = 'P' WHERE payout_id = 128;
UPDATE ?:vendor_payouts SET commission_amount = 24.45, commission = 5.00, commission_type = 'P' WHERE payout_id = 129;
UPDATE ?:vendor_payouts SET commission_amount = 12.30, commission = 10.00, commission_type = 'P' WHERE payout_id = 130;
UPDATE ?:vendor_payouts SET commission_amount = 13.75, commission = 5.00, commission_type = 'P' WHERE payout_id = 131;
UPDATE ?:vendor_payouts SET commission_amount = 14.50, commission = 5.00, commission_type = 'P' WHERE payout_id = 132;
UPDATE ?:vendor_payouts SET commission_amount = 20.60, commission = 10.00, commission_type = 'P' WHERE payout_id = 133;
UPDATE ?:vendor_payouts SET commission_amount = 32.80, commission = 10.00, commission_type = 'P' WHERE payout_id = 134;
UPDATE ?:vendor_payouts SET commission_amount = 16.15, commission = 5.00, commission_type = 'P' WHERE payout_id = 135;
UPDATE ?:vendor_payouts SET commission_amount = 41.00, commission = 10.00, commission_type = 'P' WHERE payout_id = 136;
UPDATE ?:vendor_payouts SET commission_amount = 8.05, commission = 5.00, commission_type = 'P' WHERE payout_id = 137;
UPDATE ?:vendor_payouts SET commission_amount = 18.00, commission = 10.00, commission_type = 'P' WHERE payout_id = 138;
UPDATE ?:vendor_payouts SET commission_amount = 24.45, commission = 5.00, commission_type = 'P' WHERE payout_id = 139;
UPDATE ?:vendor_payouts SET commission_amount = 17.20, commission = 10.00, commission_type = 'P' WHERE payout_id = 140;
UPDATE ?:vendor_payouts SET commission_amount = 46.20, commission = 10.00, commission_type = 'P' WHERE payout_id = 141;
UPDATE ?:vendor_payouts SET commission_amount = 36.80, commission = 10.00, commission_type = 'P' WHERE payout_id = 142;
UPDATE ?:vendor_payouts SET commission_amount = 46.90, commission = 10.00, commission_type = 'P' WHERE payout_id = 143;
UPDATE ?:vendor_payouts SET commission_amount = 18.00, commission = 10.00, commission_type = 'P' WHERE payout_id = 144;
UPDATE ?:vendor_payouts SET commission_amount = 22.40, commission = 10.00, commission_type = 'P' WHERE payout_id = 145;
UPDATE ?:vendor_payouts SET commission_amount = 16.75, commission = 5.00, commission_type = 'P' WHERE payout_id = 146;
UPDATE ?:vendor_payouts SET commission_amount = 30.70, commission = 10.00, commission_type = 'P' WHERE payout_id = 147;
UPDATE ?:vendor_payouts SET commission_amount = 22.10, commission = 10.00, commission_type = 'P' WHERE payout_id = 148;
UPDATE ?:vendor_payouts SET commission_amount = 22.30, commission = 5.00, commission_type = 'P' WHERE payout_id = 149;
UPDATE ?:vendor_payouts SET commission_amount = 11.85, commission = 5.00, commission_type = 'P' WHERE payout_id = 150;
UPDATE ?:vendor_payouts SET commission_amount = 17.25, commission = 5.00, commission_type = 'P' WHERE payout_id = 151;
UPDATE ?:vendor_payouts SET commission_amount = 10.05, commission = 5.00, commission_type = 'P' WHERE payout_id = 152;
UPDATE ?:vendor_payouts SET commission_amount = 24.45, commission = 5.00, commission_type = 'P' WHERE payout_id = 153;
UPDATE ?:vendor_payouts SET commission_amount = 23.70, commission = 10.00, commission_type = 'P' WHERE payout_id = 154;
UPDATE ?:vendor_payouts SET commission_amount = 17.80, commission = 10.00, commission_type = 'P' WHERE payout_id = 155;
UPDATE ?:vendor_payouts SET commission_amount = 48.50, commission = 10.00, commission_type = 'P' WHERE payout_id = 156;
UPDATE ?:vendor_payouts SET commission_amount = 50.60, commission = 10.00, commission_type = 'P' WHERE payout_id = 157;
UPDATE ?:vendor_payouts SET commission_amount = 13.10, commission = 10.00, commission_type = 'P' WHERE payout_id = 158;
UPDATE ?:vendor_payouts SET commission_amount = 20.60, commission = 10.00, commission_type = 'P' WHERE payout_id = 159;
UPDATE ?:vendor_payouts SET commission_amount = 40.80, commission = 10.00, commission_type = 'P' WHERE payout_id = 160;
UPDATE ?:vendor_payouts SET commission_amount = 41.90, commission = 10.00, commission_type = 'P' WHERE payout_id = 161;
UPDATE ?:vendor_payouts SET commission_amount = 32.80, commission = 10.00, commission_type = 'P' WHERE payout_id = 162;
UPDATE ?:vendor_payouts SET commission_amount = 32.80, commission = 10.00, commission_type = 'P' WHERE payout_id = 163;
UPDATE ?:vendor_payouts SET commission_amount = 23.48, commission = 1.00, commission_type = 'P' WHERE payout_id = 164;
UPDATE ?:vendor_payouts SET commission_amount = 33.63, commission = 10.00, commission_type = 'P' WHERE payout_id = 165;
UPDATE ?:vendor_payouts SET commission_amount = 0.18, commission = 10.00, commission_type = 'P' WHERE payout_id = 166;
UPDATE ?:vendor_payouts SET commission_amount = 0.18, commission = 10.00, commission_type = 'P' WHERE payout_id = 167;
UPDATE ?:vendor_payouts SET commission_amount = 0.18, commission = 10.00, commission_type = 'P' WHERE payout_id = 168;
UPDATE ?:vendor_payouts SET commission_amount = 0.18, commission = 10.00, commission_type = 'P' WHERE payout_id = 169;
UPDATE ?:vendor_payouts SET commission_amount = 6.59, commission = 10.00, commission_type = 'P' WHERE payout_id = 170;
UPDATE ?:vendor_payouts SET commission_amount = 6.59, commission = 10.00, commission_type = 'P' WHERE payout_id = 171;
UPDATE ?:vendor_payouts SET commission_amount = 6.59, commission = 10.00, commission_type = 'P' WHERE payout_id = 172;
UPDATE ?:vendor_payouts SET commission_amount = 6.59, commission = 10.00, commission_type = 'P' WHERE payout_id = 173;
UPDATE ?:vendor_payouts SET commission_amount = 5.76, commission = 10.00, commission_type = 'P' WHERE payout_id = 185;
UPDATE ?:vendor_payouts SET commission_amount = 5.76, commission = 10.00, commission_type = 'P' WHERE payout_id = 186;
UPDATE ?:vendor_payouts SET commission_amount = 5.76, commission = 10.00, commission_type = 'P' WHERE payout_id = 187;
UPDATE ?:vendor_payouts SET commission_amount = 5.76, commission = 10.00, commission_type = 'P' WHERE payout_id = 188;
UPDATE ?:vendor_payouts SET commission_amount = 3.72, commission = 10.00, commission_type = 'P' WHERE payout_id = 189;
UPDATE ?:vendor_payouts SET commission_amount = 3.72, commission = 10.00, commission_type = 'P' WHERE payout_id = 190;
UPDATE ?:vendor_payouts SET commission_amount = 3.72, commission = 10.00, commission_type = 'P' WHERE payout_id = 191;
UPDATE ?:vendor_payouts SET commission_amount = 3.72, commission = 10.00, commission_type = 'P' WHERE payout_id = 192;
UPDATE ?:vendor_payouts SET commission_amount = 7.71, commission = 10.00, commission_type = 'P' WHERE payout_id = 193;
UPDATE ?:vendor_payouts SET commission_amount = 7.71, commission = 10.00, commission_type = 'P' WHERE payout_id = 194;
UPDATE ?:vendor_payouts SET commission_amount = 7.71, commission = 10.00, commission_type = 'P' WHERE payout_id = 195;
UPDATE ?:vendor_payouts SET commission_amount = 7.71, commission = 10.00, commission_type = 'P' WHERE payout_id = 196;
UPDATE ?:vendor_payouts SET commission_amount = 6.92, commission = 10.00, commission_type = 'P' WHERE payout_id = 197;
UPDATE ?:vendor_payouts SET commission_amount = 6.92, commission = 10.00, commission_type = 'P' WHERE payout_id = 198;
UPDATE ?:vendor_payouts SET commission_amount = 6.92, commission = 10.00, commission_type = 'P' WHERE payout_id = 199;
UPDATE ?:vendor_payouts SET commission_amount = 6.92, commission = 10.00, commission_type = 'P' WHERE payout_id = 200;
UPDATE ?:vendor_payouts SET commission_amount = 8.49, commission = 1.00, commission_type = 'P' WHERE payout_id = 201;
UPDATE ?:vendor_payouts SET commission_amount = 9.22, commission = 10.00, commission_type = 'P' WHERE payout_id = 202;
UPDATE ?:vendor_payouts SET commission_amount = 9.22, commission = 10.00, commission_type = 'P' WHERE payout_id = 203;
UPDATE ?:vendor_payouts SET commission_amount = 20.09, commission = 10.00, commission_type = 'P' WHERE payout_id = 204;
UPDATE ?:vendor_payouts SET commission_amount = 5.68, commission = 10.00, commission_type = 'P' WHERE payout_id = 205;
UPDATE ?:vendor_payouts SET commission_amount = 5.68, commission = 10.00, commission_type = 'P' WHERE payout_id = 206;
UPDATE ?:vendor_payouts SET commission_amount = 5.68, commission = 10.00, commission_type = 'P' WHERE payout_id = 207;
UPDATE ?:vendor_payouts SET commission_amount = 5.68, commission = 10.00, commission_type = 'P' WHERE payout_id = 208;
UPDATE ?:vendor_payouts SET commission_amount = 1.07, commission = 1.00, commission_type = 'P' WHERE payout_id = 210;
UPDATE ?:vendor_payouts SET commission_amount = 6.95, commission = 10.00, commission_type = 'P' WHERE payout_id = 211;
UPDATE ?:vendor_payouts SET commission_amount = 4.36, commission = 5.00, commission_type = 'P' WHERE payout_id = 212;
UPDATE ?:vendor_payouts SET commission_amount = 4.48, commission = 5.00, commission_type = 'P' WHERE payout_id = 213;
UPDATE ?:vendor_payouts SET commission_amount = 5.95, commission = 5.00, commission_type = 'P' WHERE payout_id = 214;
UPDATE ?:vendor_payouts SET commission_amount = 45.85, commission = 10.00, commission_type = 'P' WHERE payout_id = 215;
UPDATE ?:vendor_payouts SET commission_amount = 5.50, commission = 10.00, commission_type = 'P' WHERE payout_id = 216;
UPDATE ?:vendor_payouts SET commission_amount = 1.07, commission = 1.00, commission_type = 'P' WHERE payout_id = 217;
UPDATE ?:vendor_payouts SET commission_amount = 8.69, commission = 10.00, commission_type = 'P' WHERE payout_id = 218;
UPDATE ?:vendor_payouts SET commission_amount = 4.15, commission = 5.00, commission_type = 'P' WHERE payout_id = 219;
UPDATE ?:vendor_payouts SET commission_amount = 4.16, commission = 5.00, commission_type = 'P' WHERE payout_id = 220;
UPDATE ?:vendor_payouts SET commission_amount = 4.47, commission = 5.00, commission_type = 'P' WHERE payout_id = 221;
UPDATE ?:vendor_payouts SET commission_amount = 9.60, commission = 10.00, commission_type = 'P' WHERE payout_id = 222;
UPDATE ?:vendor_payouts SET commission_amount = 6.70, commission = 10.00, commission_type = 'P' WHERE payout_id = 223;
UPDATE ?:vendor_payouts SET commission_amount = 5.78, commission = 5.00, commission_type = 'P' WHERE payout_id = 224;
UPDATE ?:vendor_payouts SET commission_amount = 11.48, commission = 10.00, commission_type = 'P' WHERE payout_id = 225;
UPDATE ?:vendor_payouts SET commission_amount = 3.35, commission = 5.00, commission_type = 'P' WHERE payout_id = 226;
UPDATE ?:vendor_payouts SET commission_amount = 5.78, commission = 5.00, commission_type = 'P' WHERE payout_id = 227;
UPDATE ?:vendor_payouts SET commission_amount = 11.35, commission = 10.00, commission_type = 'P' WHERE payout_id = 228;
UPDATE ?:vendor_payouts SET commission_amount = 3.35, commission = 5.00, commission_type = 'P' WHERE payout_id = 229;
UPDATE ?:vendor_payouts SET commission_amount = 3.81, commission = 5.00, commission_type = 'P' WHERE payout_id = 230;
UPDATE ?:vendor_payouts SET commission_amount = 6.48, commission = 10.00, commission_type = 'P' WHERE payout_id = 231;
UPDATE ?:vendor_payouts SET commission_amount = 0.77, commission = 1.00, commission_type = 'P' WHERE payout_id = 232;
UPDATE ?:vendor_payouts SET commission_amount = 0.66, commission = 1.00, commission_type = 'P' WHERE payout_id = 233;
UPDATE ?:vendor_payouts SET commission_amount = 1.51, commission = 1.00, commission_type = 'P' WHERE payout_id = 234;
UPDATE ?:vendor_payouts SET commission_amount = 6.95, commission = 10.00, commission_type = 'P' WHERE payout_id = 235;
UPDATE ?:vendor_payouts SET commission_amount = 6.95, commission = 10.00, commission_type = 'P' WHERE payout_id = 236;
UPDATE ?:vendor_payouts SET commission_amount = 6.95, commission = 10.00, commission_type = 'P' WHERE payout_id = 237;
UPDATE ?:vendor_payouts SET commission_amount = 6.95, commission = 10.00, commission_type = 'P' WHERE payout_id = 238;
UPDATE ?:vendor_payouts SET commission_amount = 9.60, commission = 10.00, commission_type = 'P' WHERE payout_id = 239;
UPDATE ?:vendor_payouts SET commission_amount = 4.15, commission = 5.00, commission_type = 'P' WHERE payout_id = 240;
UPDATE ?:vendor_payouts SET commission_amount = 4.15, commission = 5.00, commission_type = 'P' WHERE payout_id = 241;
UPDATE ?:vendor_payouts SET commission_amount = 4.15, commission = 5.00, commission_type = 'P' WHERE payout_id = 242;
UPDATE ?:vendor_payouts SET commission_amount = 4.16, commission = 5.00, commission_type = 'P' WHERE payout_id = 243;
UPDATE ?:vendor_payouts SET commission_amount = 4.16, commission = 5.00, commission_type = 'P' WHERE payout_id = 244;
UPDATE ?:vendor_payouts SET commission_amount = 5.95, commission = 5.00, commission_type = 'P' WHERE payout_id = 245;
UPDATE ?:vendor_payouts SET commission_amount = 9.60, commission = 10.00, commission_type = 'P' WHERE payout_id = 246;
UPDATE ?:vendor_payouts SET commission_amount = 3.81, commission = 5.00, commission_type = 'P' WHERE payout_id = 247;
UPDATE ?:vendor_payouts SET commission_amount = 6.48, commission = 10.00, commission_type = 'P' WHERE payout_id = 248;
UPDATE ?:vendor_payouts SET commission_amount = 5.78, commission = 5.00, commission_type = 'P' WHERE payout_id = 249;
UPDATE ?:vendor_payouts SET commission_amount = 5.37, commission = 5.00, commission_type = 'P' WHERE payout_id = 250;
UPDATE ?:vendor_payouts SET commission_amount = 11.48, commission = 10.00, commission_type = 'P' WHERE payout_id = 251;
UPDATE ?:vendor_payouts SET commission_amount = 5.78, commission = 5.00, commission_type = 'P' WHERE payout_id = 252;
UPDATE ?:vendor_payouts SET commission_amount = 6.70, commission = 10.00, commission_type = 'P' WHERE payout_id = 253;
UPDATE ?:vendor_payouts SET commission_amount = 11.48, commission = 10.00, commission_type = 'P' WHERE payout_id = 254;
UPDATE ?:vendor_payouts SET commission_amount = 7.11, commission = 10.00, commission_type = 'P' WHERE payout_id = 255;
