/**
 * Custom layout and logotypes go into this file. This file is applied after the demo layouts are installed.
 */

TRUNCATE TABLE `cscart_logos`;

DELETE FROM `cscart_images_links` WHERE object_type = 'logos';

REPLACE INTO `cscart_bm_block_statuses` (`snapping_id`, `object_ids`, `object_type`)
  VALUES  ((SELECT `snapping_id` FROM `cscart_bm_snapping` WHERE `user_class` = 'products__stark_industries' LIMIT 1), '26', 'pages');

REPLACE INTO `cscart_bm_block_statuses` (`snapping_id`, `object_ids`, `object_type`)
  VALUES  ((SELECT `snapping_id` FROM `cscart_bm_snapping` WHERE `user_class` = 'products__acme_corporation' LIMIT 1), '25', 'pages');

REPLACE INTO `cscart_bm_block_statuses` (`snapping_id`, `object_ids`, `object_type`)
  VALUES  ((SELECT `snapping_id` FROM `cscart_bm_snapping` WHERE `user_class` = 'block__no_transaction_fee' LIMIT 1), '27', 'pages');

REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (4,0,'',1,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (5,0,'',1,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (8,0,'',1,'favicon');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (15,0,'',0,'gift_cert');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (16,0,'',2,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (17,0,'',2,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (18,0,'',3,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (19,0,'',3,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (20,0,'',4,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (21,0,'',4,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (22,0,'',5,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (23,0,'',5,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (24,0,'',6,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (25,0,'',6,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (26,0,'',7,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (27,0,'',7,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (28,0,'',8,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (29,0,'',8,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (30,0,'',9,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (31,0,'',9,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (32,0,'',10,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (33,0,'',10,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (34,0,'',11,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (35,0,'',11,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (36,0,'',12,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (37,0,'',12,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (38,1,'Bright_theme',0,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (39,1,'Bright_theme',0,'favicon');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (40,1,'Bright_theme',0,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (41,2,'Bright_theme',0,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (42,2,'Bright_theme',0,'favicon');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (43,2,'Bright_theme',0,'mail');


REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (44,0,'',13,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (45,0,'',13,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (46,0,'',14,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (47,0,'',14,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (48,0,'',15,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (49,0,'',15,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (50,0,'',16,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (51,0,'',16,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (52,0,'',17,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (53,0,'',17,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (54,0,'',18,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (55,0,'',18,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (56,0,'',19,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (57,0,'',19,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (58,0,'',20,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (59,0,'',20,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (60,0,'',21,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (61,0,'',21,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (62,0,'',22,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (63,0,'',22,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (64,0,'',23,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (65,0,'',23,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (66,0,'',24,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (67,0,'',24,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (68,0,'',25,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (69,0,'',25,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (70,0,'',26,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (71,0,'',26,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (72,0,'',27,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (73,0,'',27,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (74,0,'',28,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (75,0,'',28,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (76,0,'',29,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (77,0,'',29,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (78,0,'',30,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (79,0,'',30,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (80,0,'',31,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (81,0,'',31,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (82,0,'',32,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (83,0,'',32,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (84,0,'',33,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (85,0,'',33,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (86,0,'',34,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (87,0,'',34,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (88,0,'',35,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (89,0,'',35,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (90,0,'',36,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (91,0,'',36,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (92,0,'',37,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (93,0,'',37,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (94,0,'',38,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (95,0,'',38,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (96,0,'',39,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (97,0,'',39,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (98,0,'',40,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (99,0,'',40,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (100,0,'',41,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (101,0,'',41,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (102,0,'',42,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (103,0,'',42,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (104,0,'',43,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (105,0,'',43,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (106,0,'',44,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (107,0,'',44,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (108,0,'',45,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (109,0,'',45,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (110,0,'',46,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (111,0,'',46,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (112,0,'',47,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (113,0,'',47,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (114,0,'',48,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (115,0,'',48,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (116,0,'',49,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (117,0,'',49,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (118,0,'',50,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (119,0,'',50,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (120,0,'',51,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (121,0,'',51,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (122,0,'',52,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (123,0,'',52,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (124,0,'',53,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (125,0,'',53,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (126,0,'',54,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (127,0,'',54,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (128,0,'',55,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (129,0,'',55,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (130,0,'',56,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (131,0,'',56,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (132,0,'',57,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (133,0,'',57,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (134,0,'',58,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (135,0,'',58,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (136,0,'',59,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (137,0,'',59,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (138,0,'',60,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (139,0,'',60,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (140,0,'',61,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (141,0,'',61,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (142,0,'',62,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (143,0,'',62,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (144,0,'',63,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (145,0,'',63,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (146,0,'',64,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (147,0,'',64,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (148,0,'',65,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (149,0,'',65,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (150,0,'',66,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (151,0,'',66,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (152,0,'',67,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (153,0,'',67,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (154,0,'',68,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (155,0,'',68,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (156,0,'',69,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (157,0,'',69,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (158,0,'',70,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (159,0,'',70,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (160,0,'',71,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (161,0,'',71,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (162,0,'',72,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (163,0,'',72,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (164,0,'',73,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (165,0,'',73,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (166,0,'',74,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (167,0,'',74,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (168,0,'',75,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (169,0,'',75,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (170,0,'',76,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (171,0,'',76,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (172,0,'',77,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (173,0,'',77,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (174,0,'',78,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (175,0,'',78,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (176,0,'',79,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (177,0,'',79,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (178,0,'',80,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (179,0,'',80,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (180,0,'',81,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (181,0,'',81,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (182,0,'',82,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (183,0,'',82,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (184,0,'',83,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (185,0,'',83,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (186,0,'',84,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (187,0,'',84,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (188,0,'',85,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (189,0,'',85,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (190,0,'',86,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (191,0,'',86,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (192,0,'',87,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (193,0,'',87,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (194,0,'',88,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (195,0,'',88,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (196,0,'',89,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (197,0,'',89,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (198,0,'',90,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (199,0,'',90,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (200,0,'',91,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (201,0,'',91,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (202,0,'',92,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (203,0,'',92,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (204,0,'',93,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (205,0,'',93,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (206,0,'',94,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (207,0,'',94,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (208,0,'',95,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (209,0,'',95,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (210,0,'',96,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (211,0,'',96,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (212,0,'',97,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (213,0,'',97,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (214,0,'',98,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (215,0,'',98,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (216,0,'',99,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (217,0,'',99,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (218,0,'',100,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (219,0,'',100,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (220,0,'',101,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (221,0,'',101,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (222,0,'',102,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (223,0,'',102,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (224,0,'',103,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (225,0,'',103,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (226,0,'',104,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (227,0,'',104,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (228,0,'',105,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (229,0,'',105,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (230,0,'',106,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (231,0,'',106,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (232,0,'',107,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (233,0,'',107,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (234,0,'',108,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (235,0,'',108,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (236,0,'',109,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (237,0,'',109,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (238,0,'',110,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (239,0,'',110,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (240,0,'',111,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (241,0,'',111,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (242,0,'',112,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (243,0,'',112,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (244,0,'',113,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (245,0,'',113,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (246,0,'',114,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (247,0,'',114,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (248,0,'',115,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (249,0,'',115,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (250,0,'',116,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (251,0,'',116,'mail');

REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (1,1,'logos',1000,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (2,2,'logos',1001,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (3,3,'logos',1002,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (4,4,'logos',1003,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (5,5,'logos',1004,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6,8,'logos',1996,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (7,9,'logos',1997,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (8,10,'logos',1998,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (9,11,'logos',1999,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (10,12,'logos',2000,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (11,13,'logos',2001,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (12,14,'logos',2002,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (13,15,'logos',2003,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (22,16,'logos',2004,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (23,17,'logos',2005,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (24,18,'logos',2006,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (25,19,'logos',2007,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (26,20,'logos',2008,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (27,21,'logos',2009,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (28,22,'logos',2010,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (29,23,'logos',2011,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (1220,24,'logos',3202,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (1221,25,'logos',3203,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (1222,26,'logos',3204,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (1223,27,'logos',3205,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (1224,0,'logos',3206,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (1225,28,'logos',3207,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (1226,29,'logos',3208,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (1227,30,'logos',3209,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (1228,31,'logos',3210,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (1229,32,'logos',3211,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (1230,33,'logos',3212,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (1231,34,'logos',3213,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (1232,35,'logos',3214,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (1233,36,'logos',3215,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (1234,37,'logos',3216,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6289,38,'logos',8271,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6290,39,'logos',8272,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6291,40,'logos',8273,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6292,41,'logos',8274,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6293,42,'logos',8275,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6294,43,'logos',8276,0,'M',0);


REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6308,44,'logos',8290,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6309,45,'logos',8290,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6310,46,'logos',8291,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6311,47,'logos',8291,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6312,48,'logos',8292,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6313,49,'logos',8292,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6314,50,'logos',8293,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6315,51,'logos',8293,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6316,52,'logos',8294,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6317,53,'logos',8294,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6318,54,'logos',8295,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6319,55,'logos',8295,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6320,56,'logos',8296,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6321,57,'logos',8296,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6322,58,'logos',8297,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6323,59,'logos',8297,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6324,60,'logos',8298,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6325,61,'logos',8298,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6326,62,'logos',8299,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6327,63,'logos',8299,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6328,64,'logos',8300,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6329,65,'logos',8300,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6330,66,'logos',8301,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6331,67,'logos',8301,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6332,68,'logos',8302,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6333,69,'logos',8302,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6334,70,'logos',8303,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6335,71,'logos',8303,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6336,72,'logos',8304,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6337,73,'logos',8304,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6338,74,'logos',8305,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6339,75,'logos',8305,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6340,76,'logos',8306,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6341,77,'logos',8306,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6342,78,'logos',8307,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6343,79,'logos',8307,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6344,80,'logos',8308,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6345,81,'logos',8308,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6346,82,'logos',8309,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6347,83,'logos',8309,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6348,84,'logos',8310,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6349,85,'logos',8310,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6350,86,'logos',8311,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6351,87,'logos',8311,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6352,88,'logos',8312,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6353,89,'logos',8312,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6354,90,'logos',8313,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6355,91,'logos',8313,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6356,92,'logos',8314,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6357,93,'logos',8314,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6358,94,'logos',8315,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6359,95,'logos',8315,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6360,96,'logos',8316,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6361,97,'logos',8316,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6362,98,'logos',8317,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6363,99,'logos',8317,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6364,100,'logos',8318,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6365,101,'logos',8318,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6366,102,'logos',8319,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6367,103,'logos',8319,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6368,104,'logos',8320,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6369,105,'logos',8320,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6370,106,'logos',8321,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6371,107,'logos',8321,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6372,108,'logos',8322,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6373,109,'logos',8322,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6374,110,'logos',8323,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6375,111,'logos',8323,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6376,112,'logos',8324,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6377,113,'logos',8324,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6378,114,'logos',8325,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6379,115,'logos',8325,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6380,116,'logos',8326,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6381,117,'logos',8326,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6382,118,'logos',8327,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6383,119,'logos',8327,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6384,120,'logos',8328,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6385,121,'logos',8328,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6386,122,'logos',8329,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6387,123,'logos',8329,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6388,124,'logos',8330,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6389,125,'logos',8330,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6390,126,'logos',8331,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6391,127,'logos',8331,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6392,128,'logos',8332,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6393,129,'logos',8332,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6394,130,'logos',8333,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6395,131,'logos',8333,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6396,132,'logos',8334,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6397,133,'logos',8334,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6398,134,'logos',8335,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6399,135,'logos',8335,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6400,136,'logos',8336,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6401,137,'logos',8336,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6402,138,'logos',8337,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6403,139,'logos',8337,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6404,140,'logos',8338,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6405,141,'logos',8338,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6406,142,'logos',8339,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6407,143,'logos',8339,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6408,144,'logos',8340,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6409,145,'logos',8340,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6410,146,'logos',8341,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6411,147,'logos',8341,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6412,148,'logos',8342,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6413,149,'logos',8342,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6414,150,'logos',8343,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6415,151,'logos',8343,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6416,152,'logos',8344,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6417,153,'logos',8344,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6418,154,'logos',8345,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6419,155,'logos',8345,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6420,156,'logos',8346,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6421,157,'logos',8346,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6422,158,'logos',8347,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6423,159,'logos',8347,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6424,160,'logos',8348,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6425,161,'logos',8348,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6426,162,'logos',8349,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6427,163,'logos',8349,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6428,164,'logos',8350,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6429,165,'logos',8350,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6430,166,'logos',8351,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6431,167,'logos',8351,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6432,168,'logos',8352,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6433,169,'logos',8352,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6434,170,'logos',8353,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6435,171,'logos',8353,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6436,172,'logos',8354,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6437,173,'logos',8354,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6438,174,'logos',8355,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6439,175,'logos',8355,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6440,176,'logos',8356,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6441,177,'logos',8356,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6442,178,'logos',8357,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6443,179,'logos',8357,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6444,180,'logos',8358,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6445,181,'logos',8358,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6446,182,'logos',8359,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6447,183,'logos',8359,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6448,184,'logos',8360,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6449,185,'logos',8360,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6450,186,'logos',8361,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6451,187,'logos',8361,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6452,188,'logos',8362,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6453,189,'logos',8362,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6454,190,'logos',8363,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6455,191,'logos',8363,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6456,192,'logos',8364,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6457,193,'logos',8364,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6458,194,'logos',8365,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6459,195,'logos',8365,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6460,196,'logos',8366,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6461,197,'logos',8366,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6462,198,'logos',8367,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6463,199,'logos',8367,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6464,200,'logos',8368,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6465,201,'logos',8368,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6466,202,'logos',8369,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6467,203,'logos',8369,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6468,204,'logos',8370,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6469,205,'logos',8370,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6470,206,'logos',8371,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6471,207,'logos',8371,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6472,208,'logos',8372,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6473,209,'logos',8372,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6474,210,'logos',8373,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6475,211,'logos',8373,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6476,212,'logos',8374,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6477,213,'logos',8374,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6478,214,'logos',8375,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6479,215,'logos',8375,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6480,216,'logos',8376,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6481,217,'logos',8376,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6482,218,'logos',8377,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6483,219,'logos',8377,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6484,220,'logos',8378,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6485,221,'logos',8378,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6486,222,'logos',8379,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6487,223,'logos',8379,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6488,224,'logos',8380,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6489,225,'logos',8380,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6490,226,'logos',8381,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6491,227,'logos',8381,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6492,228,'logos',8382,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6493,229,'logos',8382,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6494,230,'logos',8383,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6495,231,'logos',8383,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6496,232,'logos',8384,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6497,233,'logos',8384,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6498,234,'logos',8385,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6499,235,'logos',8385,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6500,236,'logos',8386,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6501,237,'logos',8386,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6502,238,'logos',8387,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6503,239,'logos',8387,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6504,240,'logos',8388,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6505,241,'logos',8388,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6506,242,'logos',8389,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6507,243,'logos',8389,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6508,244,'logos',8390,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6509,245,'logos',8390,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6510,246,'logos',8391,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6511,247,'logos',8391,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6512,248,'logos',8392,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6513,249,'logos',8392,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6514,250,'logos',8393,0,'M',0);
REPLACE INTO `cscart_images_links` (`pair_id`, `object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (6515,251,'logos',8393,0,'M',0);
