/**
 * Custom layout and logotypes go into this file. This file is applied after the demo layouts are installed.
 */

TRUNCATE TABLE `cscart_logos`;

DELETE FROM `cscart_images_links` WHERE object_type = 'logos';

REPLACE INTO `cscart_bm_block_statuses` (`snapping_id`, `object_ids`, `object_type`)
  VALUES  ((SELECT `snapping_id` FROM `cscart_bm_snapping` WHERE `user_class` = 'products__stark_industries' LIMIT 1), '26', 'pages');

REPLACE INTO `cscart_bm_block_statuses` (`snapping_id`, `object_ids`, `object_type`)
  VALUES  ((SELECT `snapping_id` FROM `cscart_bm_snapping` WHERE `user_class` = 'products__acme_corporation' LIMIT 1), '25', 'pages');

REPLACE INTO `cscart_bm_block_statuses` (`snapping_id`, `object_ids`, `object_type`)
  VALUES  ((SELECT `snapping_id` FROM `cscart_bm_snapping` WHERE `user_class` = 'block__no_transaction_fee' LIMIT 1), '27', 'pages');

REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (4,0,'',1,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (5,0,'',1,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (8,0,'',1,'favicon');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (15,0,'',0,'gift_cert');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (16,0,'',2,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (17,0,'',2,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (18,0,'',3,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (19,0,'',3,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (20,0,'',4,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (21,0,'',4,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (22,0,'',5,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (23,0,'',5,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (24,0,'',6,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (25,0,'',6,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (26,0,'',7,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (27,0,'',7,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (28,0,'',8,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (29,0,'',8,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (30,0,'',9,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (31,0,'',9,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (32,0,'',10,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (33,0,'',10,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (34,0,'',11,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (35,0,'',11,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (36,0,'',12,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (37,0,'',12,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (38,1,'Bright_theme',0,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (39,1,'Bright_theme',0,'favicon');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (40,1,'Bright_theme',0,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (41,2,'Bright_theme',0,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (42,2,'Bright_theme',0,'favicon');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (43,2,'Bright_theme',0,'mail');

REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (44,0,'',13,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (45,0,'',13,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (46,0,'',14,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (47,0,'',14,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (48,0,'',15,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (49,0,'',15,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (50,0,'',16,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (51,0,'',16,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (52,0,'',17,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (53,0,'',17,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (54,0,'',18,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (55,0,'',18,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (56,0,'',19,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (57,0,'',19,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (58,0,'',20,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (59,0,'',20,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (60,0,'',21,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (61,0,'',21,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (62,0,'',22,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (63,0,'',22,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (64,0,'',23,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (65,0,'',23,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (66,0,'',24,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (67,0,'',24,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (68,0,'',25,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (69,0,'',25,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (70,0,'',26,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (71,0,'',26,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (72,0,'',27,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (73,0,'',27,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (74,0,'',28,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (75,0,'',28,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (76,0,'',29,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (77,0,'',29,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (78,0,'',30,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (79,0,'',30,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (80,0,'',31,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (81,0,'',31,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (82,0,'',32,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (83,0,'',32,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (84,0,'',33,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (85,0,'',33,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (86,0,'',34,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (87,0,'',34,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (88,0,'',35,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (89,0,'',35,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (90,0,'',36,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (91,0,'',36,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (92,0,'',37,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (93,0,'',37,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (94,0,'',38,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (95,0,'',38,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (96,0,'',39,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (97,0,'',39,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (98,0,'',40,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (99,0,'',40,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (100,0,'',41,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (101,0,'',41,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (102,0,'',42,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (103,0,'',42,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (104,0,'',43,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (105,0,'',43,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (106,0,'',44,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (107,0,'',44,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (108,0,'',45,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (109,0,'',45,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (110,0,'',46,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (111,0,'',46,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (112,0,'',47,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (113,0,'',47,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (114,0,'',48,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (115,0,'',48,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (116,0,'',49,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (117,0,'',49,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (118,0,'',50,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (119,0,'',50,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (120,0,'',51,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (121,0,'',51,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (122,0,'',52,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (123,0,'',52,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (124,0,'',53,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (125,0,'',53,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (126,0,'',54,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (127,0,'',54,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (128,0,'',55,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (129,0,'',55,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (130,0,'',56,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (131,0,'',56,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (132,0,'',57,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (133,0,'',57,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (134,0,'',58,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (135,0,'',58,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (136,0,'',59,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (137,0,'',59,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (138,0,'',60,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (139,0,'',60,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (140,0,'',61,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (141,0,'',61,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (142,0,'',62,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (143,0,'',62,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (144,0,'',63,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (145,0,'',63,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (146,0,'',64,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (147,0,'',64,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (148,0,'',65,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (149,0,'',65,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (150,0,'',66,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (151,0,'',66,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (152,0,'',67,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (153,0,'',67,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (154,0,'',68,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (155,0,'',68,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (156,0,'',69,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (157,0,'',69,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (158,0,'',70,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (159,0,'',70,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (160,0,'',71,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (161,0,'',71,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (162,0,'',72,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (163,0,'',72,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (164,0,'',73,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (165,0,'',73,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (166,0,'',74,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (167,0,'',74,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (168,0,'',75,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (169,0,'',75,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (170,0,'',76,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (171,0,'',76,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (172,0,'',77,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (173,0,'',77,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (174,0,'',78,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (175,0,'',78,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (176,0,'',79,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (177,0,'',79,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (178,0,'',80,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (179,0,'',80,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (180,0,'',81,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (181,0,'',81,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (182,0,'',82,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (183,0,'',82,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (184,0,'',83,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (185,0,'',83,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (186,0,'',84,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (187,0,'',84,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (188,0,'',85,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (189,0,'',85,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (190,0,'',86,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (191,0,'',86,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (192,0,'',87,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (193,0,'',87,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (194,0,'',88,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (195,0,'',88,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (196,0,'',89,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (197,0,'',89,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (198,0,'',90,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (199,0,'',90,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (200,0,'',91,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (201,0,'',91,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (202,0,'',92,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (203,0,'',92,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (204,0,'',93,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (205,0,'',93,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (206,0,'',94,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (207,0,'',94,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (208,0,'',95,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (209,0,'',95,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (210,0,'',96,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (211,0,'',96,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (212,0,'',97,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (213,0,'',97,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (214,0,'',98,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (215,0,'',98,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (216,0,'',99,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (217,0,'',99,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (218,0,'',100,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (219,0,'',100,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (220,0,'',101,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (221,0,'',101,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (222,0,'',102,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (223,0,'',102,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (224,0,'',103,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (225,0,'',103,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (226,0,'',104,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (227,0,'',104,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (228,0,'',105,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (229,0,'',105,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (230,0,'',106,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (231,0,'',106,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (232,0,'',107,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (233,0,'',107,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (234,0,'',108,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (235,0,'',108,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (236,0,'',109,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (237,0,'',109,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (238,0,'',110,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (239,0,'',110,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (240,0,'',111,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (241,0,'',111,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (242,0,'',112,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (243,0,'',112,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (244,0,'',113,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (245,0,'',113,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (246,0,'',114,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (247,0,'',114,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (248,0,'',115,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (249,0,'',115,'mail');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (250,0,'',116,'theme');
REPLACE INTO `cscart_logos` (`logo_id`, `layout_id`, `style_id`, `company_id`, `type`) VALUES (251,0,'',116,'mail');


INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (1,'logos',1000,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (2,'logos',1001,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (3,'logos',1002,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (4,'logos',1003,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (5,'logos',1004,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (8,'logos',1996,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (9,'logos',1997,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (10,'logos',1998,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (11,'logos',1999,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (12,'logos',2000,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (13,'logos',2001,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (14,'logos',2002,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (15,'logos',2003,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (16,'logos',2004,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (17,'logos',2005,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (18,'logos',2006,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (19,'logos',2007,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (20,'logos',2008,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (21,'logos',2009,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (22,'logos',2010,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (23,'logos',2011,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (24,'logos',3202,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (25,'logos',3203,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (26,'logos',3204,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (27,'logos',3205,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (0,'logos',3206,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (28,'logos',3207,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (29,'logos',3208,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (30,'logos',3209,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (31,'logos',3210,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (32,'logos',3211,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (33,'logos',3212,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (34,'logos',3213,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (35,'logos',3214,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (36,'logos',3215,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (37,'logos',3216,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (38,'logos',8271,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (39,'logos',8272,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (40,'logos',8273,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (41,'logos',8274,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (42,'logos',8275,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (43,'logos',8276,0,'M',0);


INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (44,'logos',8501,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (45,'logos',8501,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (46,'logos',8502,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (47,'logos',8502,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (48,'logos',8503,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (49,'logos',8503,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (50,'logos',8504,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (51,'logos',8504,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (52,'logos',8505,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (53,'logos',8505,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (54,'logos',8506,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (55,'logos',8506,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (56,'logos',8507,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (57,'logos',8507,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (58,'logos',8508,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (59,'logos',8508,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (60,'logos',8509,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (61,'logos',8509,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (62,'logos',8510,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (63,'logos',8510,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (64,'logos',8511,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (65,'logos',8511,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (66,'logos',8512,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (67,'logos',8512,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (68,'logos',8513,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (69,'logos',8513,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (70,'logos',8514,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (71,'logos',8514,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (72,'logos',8515,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (73,'logos',8515,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (74,'logos',8516,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (75,'logos',8516,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (76,'logos',8517,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (77,'logos',8517,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (78,'logos',8518,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (79,'logos',8518,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (80,'logos',8519,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (81,'logos',8519,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (82,'logos',8520,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (83,'logos',8520,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (84,'logos',8521,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (85,'logos',8521,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (86,'logos',8522,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (87,'logos',8522,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (88,'logos',8523,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (89,'logos',8523,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (90,'logos',8524,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (91,'logos',8524,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (92,'logos',8525,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (93,'logos',8525,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (94,'logos',8526,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (95,'logos',8526,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (96,'logos',8527,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (97,'logos',8527,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (98,'logos',8528,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (99,'logos',8528,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (100,'logos',8529,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (101,'logos',8529,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (102,'logos',8530,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (103,'logos',8530,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (104,'logos',8531,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (105,'logos',8531,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (106,'logos',8532,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (107,'logos',8532,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (108,'logos',8533,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (109,'logos',8533,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (110,'logos',8534,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (111,'logos',8534,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (112,'logos',8535,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (113,'logos',8535,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (114,'logos',8536,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (115,'logos',8536,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (116,'logos',8537,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (117,'logos',8537,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (118,'logos',8538,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (119,'logos',8538,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (120,'logos',8539,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (121,'logos',8539,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (122,'logos',8540,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (123,'logos',8540,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (124,'logos',8541,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (125,'logos',8541,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (126,'logos',8542,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (127,'logos',8542,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (128,'logos',8543,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (129,'logos',8543,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (130,'logos',8544,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (131,'logos',8544,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (132,'logos',8545,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (133,'logos',8545,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (134,'logos',8546,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (135,'logos',8546,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (136,'logos',8547,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (137,'logos',8547,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (138,'logos',8548,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (139,'logos',8548,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (140,'logos',8549,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (141,'logos',8549,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (142,'logos',8550,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (143,'logos',8550,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (144,'logos',8551,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (145,'logos',8551,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (146,'logos',8552,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (147,'logos',8552,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (148,'logos',8553,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (149,'logos',8553,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (150,'logos',8554,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (151,'logos',8554,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (152,'logos',8555,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (153,'logos',8555,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (154,'logos',8556,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (155,'logos',8556,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (156,'logos',8557,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (157,'logos',8557,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (158,'logos',8558,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (159,'logos',8558,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (160,'logos',8559,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (161,'logos',8559,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (162,'logos',8560,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (163,'logos',8560,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (164,'logos',8561,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (165,'logos',8561,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (166,'logos',8562,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (167,'logos',8562,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (168,'logos',8563,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (169,'logos',8563,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (170,'logos',8564,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (171,'logos',8564,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (172,'logos',8565,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (173,'logos',8565,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (174,'logos',8566,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (175,'logos',8566,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (176,'logos',8567,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (177,'logos',8567,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (178,'logos',8568,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (179,'logos',8568,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (180,'logos',8569,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (181,'logos',8569,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (182,'logos',8570,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (183,'logos',8570,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (184,'logos',8571,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (185,'logos',8571,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (186,'logos',8572,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (187,'logos',8572,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (188,'logos',8573,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (189,'logos',8573,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (190,'logos',8574,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (191,'logos',8574,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (192,'logos',8575,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (193,'logos',8575,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (194,'logos',8576,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (195,'logos',8576,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (196,'logos',8577,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (197,'logos',8577,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (198,'logos',8578,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (199,'logos',8578,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (200,'logos',8579,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (201,'logos',8579,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (202,'logos',8580,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (203,'logos',8580,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (204,'logos',8581,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (205,'logos',8581,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (206,'logos',8582,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (207,'logos',8582,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (208,'logos',8583,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (209,'logos',8583,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (210,'logos',8584,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (211,'logos',8584,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (212,'logos',8585,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (213,'logos',8585,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (214,'logos',8586,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (215,'logos',8586,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (216,'logos',8587,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (217,'logos',8587,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (218,'logos',8588,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (219,'logos',8588,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (220,'logos',8589,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (221,'logos',8589,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (222,'logos',8590,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (223,'logos',8590,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (224,'logos',8591,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (225,'logos',8591,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (226,'logos',8592,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (227,'logos',8592,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (228,'logos',8593,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (229,'logos',8593,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (230,'logos',8594,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (231,'logos',8594,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (232,'logos',8595,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (233,'logos',8595,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (234,'logos',8596,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (235,'logos',8596,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (236,'logos',8597,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (237,'logos',8597,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (238,'logos',8598,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (239,'logos',8598,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (240,'logos',8599,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (241,'logos',8599,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (242,'logos',8600,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (243,'logos',8600,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (244,'logos',8601,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (245,'logos',8601,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (246,'logos',8602,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (247,'logos',8602,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (248,'logos',8603,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (249,'logos',8603,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (250,'logos',8604,0,'M',0);
INSERT INTO `cscart_images_links` (`object_id`, `object_type`, `image_id`, `detailed_id`, `type`, `position`) VALUES (251,'logos',8604,0,'M',0);
